#!/usr/bin/env node
// Publishes each contract's proving keys and ZK IR under public/zk/<contract>/,
// in the keys/ + zkir/ layout midnight-js's FetchZkConfigProvider requests.
//
// A browser wallet proves through the connector, but the key material has to
// come from the DApp: the wallet asks for it by URL. These are the same files
// the CLI reads from disk. They are generated by the Compact compiler, so they
// are copied at build time rather than committed.

import { cpSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const uiRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const managed = resolve(uiRoot, '../contract/managed');

for (const contract of ['nightschool']) {
  const target = resolve(uiRoot, 'public/zk', contract);
  rmSync(target, { recursive: true, force: true });
  for (const part of ['keys', 'zkir']) {
    const source = resolve(managed, contract, part);
    if (!existsSync(source)) {
      console.error(`copy-zk: ${source} is missing; build @nightschool/contract first`);
      process.exit(1);
    }
    mkdirSync(resolve(target, part), { recursive: true });
    cpSync(source, resolve(target, part), {
      recursive: true,
      // The fetcher only ever asks for binary ZK IR.
      filter: (path) => !path.endsWith('.zkir'),
    });
  }
  console.log(`copy-zk: published ${contract} keys and zkir`);
}
